### ISSUE TITLE
print help message automatically when neo called without argument

### ISSUE THREAD

**Issue by azzamsa** [BiznetGIO/neo-cli#66]

**Comment by anak10thn** [comment]
ehmmmm ini bugs yak

**Comment by azzamsa** [comment]
No. I will add this feature when neo testing done :)

**Comment by azzamsa** [comment]
This is not achievable. Since docopt manipulate the command before we can modify or append it.

We can force to use `sys.argv`. But it will add more dependencies for unimportant feature.
