### ISSUE TITLE
ADD keypairs

### ISSUE THREAD

**Issue by anak10thn** [BiznetGIO/neo-cli#77]
plis add keypairs name to list vm

**Comment by azzamsa** [comment]
DONE

![add-key](https://user-images.githubusercontent.com/17734314/43885280-a4f96a7a-9be2-11e8-9aa0-1a793ac155ab.png)

**Comment by anak10thn** [comment]
nice zam zam

**Comment by azzamsa** [comment]
Thank you, Sir.

Closing as https://github.com/BiznetGIO/neo-cli/commit/6e20b8a133ba0b75553e173fdaee1e46eac291fc
